# Generated by Django 3.2.15 on 2022-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=255, verbose_name="Nom de l'expérience")),
                ('location', models.CharField(default='Bordeaux', max_length=255, verbose_name="Lieu de l'expérience")),
                ('content', models.TextField(verbose_name="Détail de l'expérience'")),
                ('image', models.ImageField(upload_to='', verbose_name="Image de l'expérience")),
                ('logo', models.ImageField(default='logo', upload_to='', verbose_name="Logo de l'expérience")),
                ('is_active', models.BooleanField(verbose_name='Expérience active')),
                ('date_started', models.DateField(default='10/09/2022', verbose_name='Date de début')),
                ('date_ended', models.DateField(default='10/09/2022', verbose_name='Date de fin')),
                ('date_published', models.DateField(verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expérience',
                'ordering': ['-date_published'],
            },
        ),
    ]
