# Generated by Django 3.2.15 on 2022-09-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_published',
            field=models.TextField(verbose_name="Année de l'expérience"),
        ),
    ]
