# Generated by Django 3.2.15 on 2022-09-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20220916_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name': 'Expérience', 'verbose_name_plural': 'Expérience'},
        ),
    ]
