# Generated by Django 3.2.15 on 2022-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('IN', 'Informatique'), ('TH', 'Théorique'), ('ST', 'Soft-Skills')], default='IN', max_length=2, verbose_name='Catégorie'),
        ),
    ]
