# Generated by Django 3.2.15 on 2022-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date', models.CharField(max_length=255, verbose_name='Année de réalisation du projet')),
                ('category', models.CharField(choices=[('ST', 'Stage'), ('AL', 'Alternance'), ('UN', 'Université')], default='AL', max_length=2, verbose_name='Catégorie')),
                ('field', models.CharField(max_length=255, verbose_name="Domaine d'application du projet")),
                ('location', models.CharField(max_length=255, verbose_name='Lieu du projet')),
                ('picture', models.ImageField(default='logo', upload_to='', verbose_name="Image de l'expérience")),
                ('is_active', models.BooleanField(verbose_name='Projet active')),
                ('content', models.TextField(verbose_name='Détail du projet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projet',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.TextField(verbose_name="Détail de l'expérience"),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='logo', upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
